import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { MyContextProvider } from "@/components/MyContext";
const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "For The Sake Of Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyContextProvider>
          <NavBar />
          {children}
        </MyContextProvider>
      </body>
    </html>
  );
}
